@startuml Signing Scheme
title FROST Signing Diagram
participant Aggregator as agg #Yellow
participant Participant_1 as p1
participant Participant_2 as p2


!pragma teoz true


p1 -> p1 : init_pub_share
& p2 -> p2 : init_pub_share

p1 --> agg : pub_share_packet
p2 --> agg : pub_share_packet

agg -> agg : init_tuple_packet

note left of agg : Broadcast
agg ->> p1 : tuple_packet
& agg ->> p2 
note left of agg : End of \nBroadcast

p1 -> p1 : init_sec_share\nand \ndelete (d,D)
& p2 -> p2 : init_sec_share\nand \ndelete (d,D)

p1 --> agg : sec_share_packet
& agg <- agg : verify

p2 --> agg : sec_share_packet
& agg <- agg : verify

agg -> agg : group response
hnote over agg : pubish_sig

@enduml